-- Migration Script: Fix Identity Columns for Restore / Sync Functionality
-- Run this script in your Supabase SQL Editor (https://supabase.com/dashboard/project/zfqksxmlcffxmhcbpsus/sql/new)
-- to allow restoring deleted records with their original IDs.

-- 1. Alter clients table identity type
ALTER TABLE public.clients ALTER COLUMN id SET GENERATED BY DEFAULT;

-- 2. Alter inquiries table identity type
ALTER TABLE public.inquiries ALTER COLUMN id SET GENERATED BY DEFAULT;

-- 3. Alter projects table identity type
ALTER TABLE public.projects ALTER COLUMN id SET GENERATED BY DEFAULT;

-- 4. Alter project milestones table identity type
ALTER TABLE public.project_milestones ALTER COLUMN id SET GENERATED BY DEFAULT;

-- 5. Alter project activity logs table identity type
ALTER TABLE public.project_activity_logs ALTER COLUMN id SET GENERATED BY DEFAULT;

-- 6. Alter project chats table identity type
ALTER TABLE public.project_chats ALTER COLUMN id SET GENERATED BY DEFAULT;

-- 7. Alter project media table identity type
ALTER TABLE public.project_media ALTER COLUMN id SET GENERATED BY DEFAULT;

-- 8. Alter invoices table identity type
ALTER TABLE public.invoices ALTER COLUMN id SET GENERATED BY DEFAULT;
